spring.application.name=adoptions
#
spring.sql.init.mode=always
#
spring.datasource.url=jdbc:postgresql://localhost:5433/postgresml
spring.datasource.username=postgresml
spring.datasource.password=
#
spring.ai.postgresml.embedding.create-extension=true
spring.ai.postgresml.embedding.options.vector-type=pg_vector
#
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.initialize-schema=true
#
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
#
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
#
spring.ai.anthropic.api-key: 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
spring.ai.anthropic.chat.options.model=claude-sonnet-4-5
spring.ai.anthropic.chat.options.temperature=0.2